# Generated by Django 5.2.7 on 2025-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo_referencia',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
