# Generated by Django 5.2.7 on 2025-10-05 21:59

from django.db import migrations


def create_initial_empresa(apps, schema_editor):
    """Crear la empresa inicial Monital S.R.L."""
    User = apps.get_model('api', 'User')
    Empresa = apps.get_model('api', 'Empresa')
    
    # Obtener el primer usuario creado
    primer_usuario = User.objects.first()
    
    if primer_usuario:
        # Crear la empresa inicial
        Empresa.objects.create(
            razon_social='Monital S.R.L',
            nombre_comercial='Monital',
            ruc='80008811-5',
            direccion='Avenida Aviadores del Chaco 2917, Asunción',
            usuario_creacion=primer_usuario,
            correo_referencia='marketing@monital.com.py',
            numero_referencia='(021) 620 4000',
            activo=True
        )


def reverse_create_initial_empresa(apps, schema_editor):
    """Eliminar la empresa inicial si se revierte la migración."""
    Empresa = apps.get_model('api', 'Empresa')
    Empresa.objects.filter(ruc='80008811-5').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empresa_correo_referencia_empresa_numero_referencia'),
    ]

    operations = [
        migrations.RunPython(create_initial_empresa, reverse_create_initial_empresa),
    ]
