# Generated by Django 5.2.7 on 2025-10-09 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20251005_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.empresa'),
        ),
    ]
