# Generated by Django 5.2.7 on 2025-10-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_id_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
