# Generated by Django 5.2.7 on 2025-10-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_empresa',
            new_name='empresa',
        ),
    ]
