# Generated by Django 5.2.7 on 2025-10-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_id_empresa_user_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=2, null=True)),
                ('identificador_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('codigo_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_cliente', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_estacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_estacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('documento_chofer', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_chofer', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='api.empresa', to_field='ruc')),
            ],
            options={
                'db_table': 'api_venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='api.venta')),
            ],
            options={
                'db_table': 'api_venta_linea',
                'ordering': ['id'],
            },
        ),
    ]
