# Generated by Django 5.2.7 on 2025-10-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_venta_ventalinea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='rut_cliente',
            new_name='ruc_cliente',
        ),
    ]
