# Generated by Django 5.2.7 on 2025-10-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_rut_cliente_venta_ruc_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_empresa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
