# Generated by Django 5.2.7 on 2025-10-14 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_venta_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='api.empresa'),
        ),
    ]
