# Generated by Django 5.2.7 on 2025-10-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_venta_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_empresa',
        ),
    ]
