# Generated by Django 5.2.7 on 2025-10-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_venta_id_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_matricula', models.CharField(max_length=50, unique=True)),
                ('cod_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='api.empresa')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_creadas', to='api.user')),
            ],
            options={
                'db_table': 'api_matricula',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='matricula_obj',
            field=models.ForeignKey(blank=True, db_column='matricula_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='api.matricula'),
        ),
    ]
