# Generated by Django 5.2.7 on 2025-10-14 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_matricula_venta_matricula_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='matricula_obj',
            new_name='matricula_id',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
