# Generated by Django 5.2.7 on 2025-10-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_matricula_obj_venta_matricula_id_and_more'),
        ('api', '0015_seed_api_user'),
    ]

    operations = [
    ]
