# Generated by Django 5.2.7 on 2025-10-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20251014_2059'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward migration - crear la vista
            sql="""
                CREATE OR REPLACE VIEW vw_venta_detalle AS
                SELECT 
                    v.tipo,
                    v.identificador_tr,
                    v.ticket,
                    v.fecha,
                    v.codigo_cliente,
                    v.ruc_cliente,
                    v.nombre_cliente,
                    v.codigo_estacion,
                    v.nombre_estacion,
                    v.codigo_moneda,
                    v.nombre_chofer,
                    v.matricula,
                    vl.codigo_producto,
                    vl.nombre_producto,
                    vl.cantidad,
                    vl.precio_unitario,
                    vl.subtotal,
                    v.id as venta_id,
                    v.empresa_id,
                    v.matricula_id
                FROM api_venta v
                LEFT JOIN api_venta_linea vl ON vl.venta_id = v.id 
                ORDER BY vl.id DESC;
            """,
            # Reverse migration - eliminar la vista
            reverse_sql="""
                DROP VIEW IF EXISTS vw_venta_detalle;
            """
        ),
    ]
