# Generated by Django 5.2.7 on 2025-10-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_create_venta_detalle_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('venta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=2, null=True)),
                ('identificador_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('codigo_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc_cliente', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_estacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_estacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_chofer', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('matricula_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'vw_venta_detalle',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='cod_interno',
            new_name='tracker_id',
        ),
    ]
