# Generated by Django 5.2.7 on 2025-11-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ventadetalle_rename_cod_interno_matricula_tracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_autorizacion_vale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_vale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
