# Generated by Django 5.2.7 on 2025-11-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_venta_numero_autorizacion_vale_venta_numero_vale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalinea',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
