# Generated by Django 5.2.7 on 2025-11-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ventalinea_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventalinea',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='ventalinea',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
